sr: 16000
training_dataset_dir: /Users/ezajlerg/datasets/pnn_dataset/reverb_moving/train/
validation_dataset_dir: /Users/ezajlerg/datasets/pnn_dataset/reverb_moving/validation/
test_dataset_dir: /Users/ezajlerg/datasets/pnn_dataset/libri_adhoc_40_4mics/test
num_mics: 4
sample_duration_in_seconds: 1
n_max_sources: 1
name: "distributed_ssl"